# Generated by Django 6.1 on 2026-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='compatibility_score',
            field=models.FloatField(default=0.0, verbose_name='Процент совместимости'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_onboarded',
            field=models.BooleanField(default=False, verbose_name='Онбординг пройден'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.TextField(blank=True, null=True, verbose_name='Образ жизни (через запятую)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('relationship', 'Отношения'), ('friends', 'Друзья'), ('communication', 'Общение'), ('business', 'Деловые знакомства')], max_length=20, null=True, verbose_name='Кого ищете'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип личности (MBTI)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='values',
            field=models.TextField(blank=True, null=True, verbose_name='Ценности (через запятую)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Знак зодиака'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Интересы (через запятую)'),
        ),
    ]
