# Generated by Django 6.1 on 2026-08-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_charactertrait_group_interest_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
